export { createDb, type Db, type DbHandle } from './client.ts';
export { withTenant, type TenantTx } from './tenant.ts';
export { applyMigrations } from './migrate.ts';
export { writeAuditEntry, type AuditEntry } from './audit.ts';
export * as schema from './schema/index.ts';
export {
  listFrameworks,
  getFramework,
  getRequirementTree,
  listControls,
  listControlLinks,
  listScopes,
  activateFrameworkOnScope,
  createControl,
  mapControlToRequirement,
  unmapControlFromRequirement,
  getControlDeleteImpact,
  deleteControl,
  createCustomFramework,
  addCustomRequirement,
  type FrameworkSummary,
  type RequirementNode,
  type ControlSummary,
  type ControlLink,
  type ScopeSummary,
  type CreateControlInput,
  type CreateCustomFrameworkInput,
  type AddCustomRequirementInput,
} from './queries/referentiels.ts';
export {
  createAssessment,
  listAssessments,
  getAssessmentItems,
  setAssessmentItemStatus,
  getMutualizedPeers,
  getSoaHeader,
  closeAssessment,
  type CreateAssessmentInput,
  type AssessmentSummary,
  type AssessmentItemRow,
  type SetItemStatusInput,
  type MutualizedPeerRow,
  type SoaHeader,
} from './queries/assessments.ts';
export {
  claimNextExport,
  createExport,
  sealExport,
  failExport,
  getExport,
  listExportsForObject,
  getExportPdf,
  verifyExport,
  type ClaimedExport,
  type CreateExportInput,
  type SealExportInput,
  type ExportSummary,
  type VerifiedExport,
} from './queries/exports.ts';
export {
  getActiveScale,
  ensureDefaultScale,
  createRisk,
  updateRiskRating,
  updateRiskDetails,
  listRisks,
  acceptRisk,
  linkRiskControl,
  unlinkRiskControl,
  listRiskHistory,
  type StoredScale,
  type CreateRiskInput,
  type UpdateRiskRatingInput,
  type UpdateRiskDetailsInput,
  type RiskSummary,
  type AcceptRiskInput,
  type RiskHistoryRow,
} from './queries/risks.ts';
