export { createDb, type Db, type DbHandle } from './client.ts';
export { withTenant, type TenantTx } from './tenant.ts';
export { applyMigrations } from './migrate.ts';
export { writeAuditEntry, type AuditEntry } from './audit.ts';
export * as schema from './schema/index.ts';
export {
  listFrameworks,
  getFramework,
  getRequirementTree,
  listControls,
  listControlLinks,
  listScopes,
  activateFrameworkOnScope,
  createControl,
  mapControlToRequirement,
  unmapControlFromRequirement,
  getControlDeleteImpact,
  deleteControl,
  createCustomFramework,
  addCustomRequirement,
  type FrameworkSummary,
  type RequirementNode,
  type ControlSummary,
  type ControlLink,
  type ScopeSummary,
  type CreateControlInput,
  type CreateCustomFrameworkInput,
  type AddCustomRequirementInput,
} from './queries/referentiels.ts';
export {
  createAssessment,
  listAssessments,
  getAssessmentItems,
  setAssessmentItemStatus,
  getMutualizedPeers,
  getSoaHeader,
  closeAssessment,
  type CreateAssessmentInput,
  type AssessmentSummary,
  type AssessmentItemRow,
  type SetItemStatusInput,
  type MutualizedPeerRow,
  type SoaHeader,
} from './queries/assessments.ts';
export {
  claimNextExport,
  createExport,
  sealExport,
  failExport,
  getExport,
  listExportsForObject,
  getExportPdf,
  verifyExport,
  type ClaimedExport,
  type CreateExportInput,
  type SealExportInput,
  type ExportSummary,
  type VerifiedExport,
} from './queries/exports.ts';
export {
  getActiveScale,
  ensureDefaultScale,
  createRisk,
  updateRiskRating,
  updateRiskDetails,
  listRisks,
  acceptRisk,
  linkRiskControl,
  unlinkRiskControl,
  listRiskControlIds,
  listRiskHistory,
  type StoredScale,
  type CreateRiskInput,
  type UpdateRiskRatingInput,
  type UpdateRiskDetailsInput,
  type RiskSummary,
  type AcceptRiskInput,
  type RiskHistoryRow,
} from './queries/risks.ts';
export { listTenantMembers, type TenantMember } from './queries/members.ts';
export { listAuditLog, type AuditRow } from './queries/audit.ts';
export {
  createSupplier,
  updateSupplier,
  listSuppliers,
  type SupplierTier,
  type ContractStatus,
  type CreateSupplierInput,
  type UpdateSupplierInput,
  type SupplierSummary,
} from './queries/suppliers.ts';
export { getDashboardMetrics, type DashboardMetrics } from './queries/dashboard.ts';
export {
  createNc,
  updateNcSteps,
  closeNc,
  confirmEffective,
  reopenNc,
  listNc,
  getNc,
  type CreateNcInput,
  type UpdateNcInput,
  type NcSummary,
  type NcDetail,
  type NcCorrectiveAction,
} from './queries/nonconformities.ts';
export {
  createIncident,
  qualifyIncident,
  addEvent,
  markNotificationSent,
  closeIncident,
  listIncidents,
  getIncident,
  type CreateIncidentInput,
  type QualifyInput,
  type CloseResult,
  type IncidentSummary,
  type IncidentDetail,
} from './queries/incidents.ts';
export {
  createAsset,
  bulkCreateAssets,
  listAssets,
  linkAssetRisk,
  unlinkAssetRisk,
  listAssetRiskIds,
  type CreateAssetInput,
  type AssetSummary,
} from './queries/assets.ts';
export {
  createEvidence,
  listEvidences,
  getEvidenceContent,
  linkEvidence,
  unlinkEvidence,
  listEvidenceLinks,
  listEvidencesCoveringRequirement,
  logAccess,
  listAccessLog,
  type EvidenceTarget,
  type CreateEvidenceInput,
  type EvidenceSummary,
  type EvidenceContent,
  type EvidenceLinkRow,
  type CoveringEvidence,
  type AccessLogRow,
} from './queries/evidences.ts';
export {
  createDocument,
  addVersion,
  publishVersion,
  listDocuments,
  listVersions,
  latestSemver,
  getVersionContent,
  linkRequirement,
  unlinkRequirement,
  listDocumentRequirementIds,
  listDocumentsCoveringRequirement,
  type CreateDocumentInput,
  type AddVersionInput,
  type DocumentSummary,
  type DocumentVersionRow,
  type VersionContent,
  type CoveringDocument,
} from './queries/documents.ts';
export {
  createAction,
  listActions,
  updateActionDetails,
  setActionStatus,
  bulkSetStatus,
  addSubtask,
  setSubtaskDone,
  addComment,
  linkAction,
  unlinkAction,
  getActionDetail,
  type ActionLinkTarget,
  type CreateActionInput,
  type ActionSummary,
  type ActionFilter,
  type UpdateActionInput,
  type ActionSubtaskRow,
  type ActionCommentRow,
  type ActionLinkRow,
  type ActionDetail,
} from './queries/actions.ts';
