/**
 * Journal d'audit (plan §8.2) : libellés lisibles des codes d'action et des
 * types d'objet, et filtres par famille d'actions. Le code brut reste la
 * donnée de référence (infobulle, export CSV) ; un code inconnu s'affiche
 * tel quel plutôt que de disparaître.
 */

/**
 * Filtres de l'écran du journal, par préfixe d'action. Chaque action
 * libellée ci-dessous relève d'un filtre (vérifié par les tests).
 */
export const AUDIT_ACTION_FILTERS: readonly { label: string; prefix: string }[] = [
  { label: 'Toutes les actions', prefix: '' },
  { label: 'Organisation (profil, modules)', prefix: 'organisation.' },
  { label: 'Entités juridiques', prefix: 'entity.' },
  { label: 'Sites', prefix: 'site.' },
  { label: 'Périmètres', prefix: 'scope.' },
  { label: 'Membres', prefix: 'membership.' },
  { label: 'Invitations', prefix: 'invitation.' },
  { label: 'Référentiels', prefix: 'framework.' },
  { label: 'Exigences personnalisées', prefix: 'requirement.' },
  { label: 'Contrôles', prefix: 'control.' },
  { label: 'Évaluations', prefix: 'assessment.' },
  { label: 'Risques', prefix: 'risk.' },
  { label: 'EBIOS RM', prefix: 'ebios.' },
  { label: 'Actifs', prefix: 'asset.' },
  { label: 'Plan d’action', prefix: 'action.' },
  { label: 'Documents', prefix: 'document.' },
  { label: 'Preuves', prefix: 'evidence.' },
  { label: 'Incidents', prefix: 'incident.' },
  { label: 'Obligations', prefix: 'obligation.' },
  { label: 'Traitements de données', prefix: 'processing.' },
  { label: 'Fournisseurs', prefix: 'supplier.' },
  { label: 'Portail fournisseur', prefix: 'supplier_portal.' },
  { label: 'Dérogations', prefix: 'exception.' },
  { label: 'Audits internes', prefix: 'audit.' },
  { label: 'Revue de direction', prefix: 'review.' },
  { label: 'Processus', prefix: 'process.' },
  { label: 'Non-conformités', prefix: 'nc.' },
  { label: 'Sensibilisation', prefix: 'training.' },
  { label: 'Continuité d’activité', prefix: 'continuity.' },
  { label: 'Satisfaction client', prefix: 'satisfaction.' },
  { label: 'Livrables scellés', prefix: 'export.' },
  { label: 'Exports de registres', prefix: 'register.' },
  { label: 'Import', prefix: 'import.' },
  { label: 'Export complet des données', prefix: 'tenant.' },
  { label: 'Fichiers bloqués', prefix: 'upload.' },
  { label: 'Journal (vérifications, exports)', prefix: 'journal.' },
];

export const AUDIT_ACTION_LABEL: Readonly<Record<string, string>> = {
  'organisation.create': 'Création de l’organisation',
  'organisation.update': 'Modification du profil de l’organisation',
  'organisation.modules': 'Activation ou désactivation de modules',
  'entity.create': 'Ajout d’une entité juridique',
  'entity.update': 'Modification d’une entité juridique',
  'entity.delete': 'Suppression d’une entité juridique',
  'site.create': 'Ajout d’un site',
  'site.update': 'Modification d’un site',
  'site.delete': 'Suppression d’un site',
  'scope.create': 'Création d’un périmètre',
  'scope.update': 'Modification d’un périmètre',
  'scope.delete': 'Suppression d’un périmètre',
  'membership.accept_invitation': 'Arrivée d’un membre (invitation acceptée)',
  'membership.change_role': 'Changement de rôle',
  'membership.remove': 'Retrait d’un membre',
  'invitation.create': 'Invitation d’un membre',
  'invitation.revoke': 'Révocation d’une invitation',
  'framework.activate': 'Activation d’un référentiel',
  'framework.create_custom': 'Création d’un référentiel personnalisé',
  'framework.hide': 'Masquage d’un référentiel',
  'framework.restore': 'Réaffichage d’un référentiel',
  'requirement.create_custom': 'Ajout d’une exigence personnalisée',
  'control.create': 'Création d’un contrôle',
  'control.update': 'Modification d’un contrôle',
  'control.delete': 'Suppression d’un contrôle',
  'control.map': 'Rattachement d’un contrôle à une exigence',
  'control.unmap': 'Détachement d’un contrôle d’une exigence',
  'control.review': 'Revue d’efficacité d’un contrôle',
  'control.templates_adopt': 'Reprise de contrôles types',
  'control.corrective_action': 'Action corrective issue d’une revue de contrôle',
  'assessment.create': 'Ouverture d’une campagne d’évaluation',
  'assessment.set_status': 'Évaluation d’une exigence',
  'assessment.close': 'Clôture d’une campagne d’évaluation',
  'risk.create': 'Création d’un risque',
  'risk.update': 'Modification d’un risque',
  'risk.rate': 'Cotation d’un risque',
  'risk.accept': 'Acceptation formelle d’un risque',
  'risk.treatment_action': 'Action de traitement d’un risque',
  'risk.control_link': 'Rattachement d’un contrôle à un risque',
  'risk.control_unlink': 'Détachement d’un contrôle d’un risque',
  'ebios.create': 'Création d’une étude EBIOS RM',
  'ebios.generate_risk': 'Risque créé depuis un scénario EBIOS RM',
  'asset.create': 'Ajout d’un actif',
  'asset.import_csv': 'Import d’actifs (CSV)',
  'asset.link_risk': 'Rattachement d’un actif à un risque',
  'asset.unlink_risk': 'Détachement d’un actif d’un risque',
  'action.create': 'Création d’une action',
  'action.update': 'Modification d’une action',
  'action.status': 'Changement de statut d’une action',
  'action.bulk_status': 'Changement de statut de plusieurs actions',
  'action.create_from_gap': 'Action créée depuis un écart d’évaluation',
  'document.create': 'Création d’un document',
  'document.version_add': 'Dépôt d’une version de document',
  'document.version_write': 'Rédaction d’une version de document',
  'document.publish': 'Publication d’un document',
  'document.acknowledgement_required': 'Demande de prise de connaissance',
  'document.acknowledge': 'Prise de connaissance d’un document',
  'evidence.create': 'Dépôt d’une preuve',
  'evidence.renew': 'Renouvellement d’une preuve',
  'evidence.link': 'Rattachement d’une preuve à un contrôle',
  'evidence.unlink': 'Détachement d’une preuve d’un contrôle',
  'incident.create': 'Déclaration d’un incident',
  'incident.qualify': 'Qualification d’un incident',
  'incident.close': 'Clôture d’un incident',
  'obligation.create': 'Ajout d’une obligation',
  'obligation.update': 'Modification d’une obligation',
  'obligation.delete': 'Suppression d’une obligation',
  'obligation.suggestions': 'Ajout des obligations suggérées',
  'processing.create': 'Création d’un traitement de données',
  'processing.update': 'Modification d’un traitement de données',
  'processing.delete': 'Suppression d’un traitement de données',
  'supplier.create': 'Ajout d’un fournisseur',
  'supplier.update': 'Modification d’un fournisseur',
  'supplier.assessment': 'Évaluation d’un fournisseur',
  'supplier.attestation.add': 'Ajout d’une attestation fournisseur',
  'supplier.attestation.remove': 'Retrait d’une attestation fournisseur',
  'supplier.corrective_action': 'Action corrective fournisseur',
  'supplier.request_create': 'Envoi d’un questionnaire fournisseur',
  'supplier.request_renew': 'Prolongation d’un questionnaire fournisseur',
  'supplier.request_cancel': 'Annulation d’un questionnaire fournisseur',
  'supplier.request_validate': 'Validation des réponses d’un fournisseur',
  'supplier_portal.save': 'Brouillon enregistré par un fournisseur',
  'supplier_portal.submit': 'Réponses transmises par un fournisseur',
  'exception.request': 'Demande de dérogation',
  'exception.renew': 'Demande de renouvellement d’une dérogation',
  'exception.update': 'Modification d’une dérogation',
  'exception.approve': 'Approbation d’une dérogation',
  'exception.refuse': 'Refus d’une dérogation',
  'exception.close': 'Clôture d’une dérogation',
  'audit.create': 'Planification d’un audit interne',
  'audit.finding_add': 'Constat d’audit',
  'audit.finding_to_action': 'Action issue d’un constat d’audit',
  'review.create': 'Création d’une revue de direction',
  'review.decision_to_action': 'Action issue d’une décision de revue',
  'process.create': 'Création d’un processus',
  'nc.create': 'Déclaration d’une non-conformité',
  'nc.update': 'Modification d’une non-conformité',
  'nc.corrective_action': 'Action corrective de non-conformité',
  'nc.close': 'Clôture d’une non-conformité',
  'nc.confirm': 'Confirmation de l’efficacité des actions correctives',
  'nc.reopen': 'Réouverture d’une non-conformité',
  'training.create': 'Création d’une session de formation',
  'training.update': 'Modification d’une session de formation',
  'training.delete': 'Suppression d’une session de formation',
  'training.attach_sheet': 'Dépôt d’une feuille d’émargement',
  'continuity.activity_create': 'Ajout d’une activité au bilan d’impact',
  'continuity.activity_update': 'Modification d’une activité du bilan d’impact',
  'continuity.activity_delete': 'Suppression d’une activité du bilan d’impact',
  'continuity.exercise_create': 'Planification d’un exercice de continuité',
  'continuity.exercise_update': 'Modification d’un exercice de continuité',
  'continuity.exercise_delete': 'Suppression d’un exercice de continuité',
  'continuity.exercise_report': 'Rapport d’exercice de continuité rattaché',
  'continuity.exercise_action': 'Action issue d’un exercice de continuité',
  'satisfaction.survey_create': 'Création d’une enquête de satisfaction',
  'satisfaction.survey_update': 'Modification d’une enquête de satisfaction',
  'satisfaction.survey_delete': 'Suppression d’une enquête de satisfaction',
  'satisfaction.survey_report': 'Rapport d’enquête de satisfaction rattaché',
  'export.request': 'Demande de livrable scellé',
  'register.export': 'Export CSV d’un registre',
  'import.apply': 'Import de données',
  'tenant.export': 'Export complet des données',
  'upload.malware_blocked': 'Fichier bloqué par l’antivirus',
  'journal.verify': 'Vérification de l’intégrité du journal',
  'journal.export': 'Export CSV du journal',
};

export const AUDIT_OBJECT_LABEL: Readonly<Record<string, string>> = {
  organisation: 'Organisation',
  legal_entity: 'Entité juridique',
  site: 'Site',
  scope: 'Périmètre',
  scope_framework: 'Référentiel activé',
  membership: 'Membre',
  invitation: 'Invitation',
  framework: 'Référentiel',
  requirement: 'Exigence',
  control: 'Contrôle',
  control_requirement: 'Rattachement contrôle–exigence',
  assessment: 'Campagne d’évaluation',
  assessment_item: 'Exigence évaluée',
  risk: 'Risque',
  risk_acceptance: 'Acceptation de risque',
  risk_control: 'Rattachement risque–contrôle',
  ebios_study: 'Étude EBIOS RM',
  asset: 'Actif',
  action: 'Action',
  document: 'Document',
  document_version: 'Version de document',
  evidence: 'Preuve',
  incident: 'Incident',
  obligation: 'Obligation',
  processing_activity: 'Traitement de données',
  supplier: 'Fournisseur',
  supplier_request: 'Questionnaire fournisseur',
  policy_exception: 'Dérogation',
  audit: 'Audit interne',
  review: 'Revue de direction',
  process: 'Processus',
  nonconformity: 'Non-conformité',
  training_session: 'Session de formation',
  continuity_activity: 'Activité (bilan d’impact)',
  continuity_exercise: 'Exercice de continuité',
  customer_survey: 'Enquête de satisfaction',
  export: 'Livrable scellé',
  registre: 'Registre',
  upload: 'Fichier déposé',
  journal: 'Journal d’audit',
};

export function auditActionLabel(code: string): string {
  return Object.hasOwn(AUDIT_ACTION_LABEL, code) ? AUDIT_ACTION_LABEL[code]! : code;
}

export function auditObjectLabel(code: string): string {
  return Object.hasOwn(AUDIT_OBJECT_LABEL, code) ? AUDIT_OBJECT_LABEL[code]! : code;
}
